# Generated by Django 5.1 on 2024-08-29 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256, verbose_name='Nome')),
                ('census', models.CharField(max_length=10, unique=True, verbose_name='Censo')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.CharField(max_length=1, verbose_name='Nome da Turma')),
                ('year', models.CharField(max_length=10, verbose_name='Ano')),
                ('cod_classroom', models.CharField(max_length=10, verbose_name='Codigo da turma')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.school')),
            ],
            options={
                'verbose_name': 'ClassRoom',
                'ordering': ('room', 'year'),
            },
        ),
    ]
