# Generated by Django 5.1 on 2024-08-13 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.CharField(max_length=1, verbose_name='Nome da Turma')),
                ('year', models.CharField(max_length=10, verbose_name='Ano')),
                ('cod_classroom', models.CharField(max_length=10, verbose_name='Codigo da turma')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.school')),
            ],
            options={
                'verbose_name': 'ClassRoom',
                'ordering': ('room', 'year'),
            },
        ),
    ]
