# Generated by Django 5.1 on 2024-08-29 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hexadecimal', models.CharField(max_length=16, verbose_name='Hexadecimal')),
                ('pedagogical_observation', models.TextField()),
                ('alternative', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e')], max_length=1, verbose_name='Alternative')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('response', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e')], max_length=1, verbose_name='Response')),
                ('question_reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.questiontest')),
            ],
            options={
                'verbose_name': 'Student Response',
                'verbose_name_plural': 'Student Responses',
            },
        ),
        migrations.CreateModel(
            name='SchoolTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school_supplies', models.CharField(choices=[('PORTUGUES', 'Português'), ('MATEMATICA', 'Matemática')], max_length=50, verbose_name='Materia escolar')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
                ('student_response', models.ManyToManyField(related_name='school_test_student_response', to='exams.studentresponse')),
            ],
            options={
                'verbose_name': 'School test',
                'verbose_name_plural': 'School tests',
            },
        ),
        migrations.CreateModel(
            name='TestAnswerSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rooms', models.CharField(choices=[('1° AO 5°', '1° ao 5°'), ('6°', '6°'), ('7°', '7°'), ('8°', '8°'), ('9°', '9°')], max_length=10, verbose_name='Turmas')),
                ('school_supplies', models.CharField(choices=[('PORTUGUES', 'Português'), ('MATEMATICA', 'Matemática')], max_length=50, verbose_name='Materia escolar')),
                ('correct_answer', models.ManyToManyField(related_name='questions_test_answer_sheet', to='exams.questiontest')),
            ],
            options={
                'verbose_name': 'Test Answer Sheet',
                'verbose_name_plural': 'Tests Answer Sheet',
            },
        ),
    ]
