# Generated by Django 5.1 on 2024-08-15 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionTest',
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('response', models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e')], max_length=1, verbose_name='Response')),
                ('question_reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.questiontest')),
            ],
            options={
                'verbose_name': 'Student Response',
                'verbose_name_plural': 'Student Responses',
            },
        ),
        migrations.AlterField(
            model_name='schooltest',
            name='student_response',
            field=models.ManyToManyField(related_name='school_test_student_response', to='exams.studentresponse'),
        ),
    ]
