# Generated by Django 5.1 on 2024-08-29 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Ultimo nome')),
                ('inep', models.CharField(max_length=12, unique=True, verbose_name='INEP')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.school')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ('first_name', 'last_name'),
            },
        ),
    ]
